// AUTO-GENERATED by `pnpm sync` (scripts/sync-data.mjs). Do not hand-edit.
// Pre-baked summary metadata catalog for tracked models.
export interface MetaFile {
  id: string;
  name: string;
  short: string;
  contextWindow: string;
  modalities: string;
  pricingNote: string;
  pricingTiers?: string[];
  freeTierNote?: string;
  noFreeId?: boolean;
}

export const GENERATED_CATALOG: Record<string, MetaFile> = {};
