// AUTO-GENERATED by `pnpm sync` (scripts/sync-data.mjs). Do not hand-edit.
// Registry of reporting agents and virtual views.

export type SourceKey =
  | "average"
  | "big-pickle"
  | "Muse Spark 1.3"
  | "Gemini 3.5 Flash Lite"
  | "Gemini 3.6 Flash"
  | "GLM 5.3 Flash"
  | "Ox Alpha"
  | "Claude Sonnet 4.6"
  | "DeepSeek 4.1 Flash"
  | "Solar Pro 4"
  | "MiniMax M3"
  | "GPT 5.6 Terra"
  | "Gemini 3.5 Flash"
  | "Claude Opus 4.6"
  | "Gemini 3.8 Flash"
  | "Grok 4.6"
  | "Gemini 3.7 Flash"
  | "Laguna S 2.1"
  | "GLM 5.2 Coding"
  | "Mimo v2.6 Flash"
  | "tool"
  | "reason"
  | "context"
  | "cost"
  | "code"
  | "multi"
  | "Mimo v2.5 Free"
  | "Muse Spark 1.2"
  | "Claude Sonnet 4.5"
  | "Claude Sonnet 5"
  | "GPT 5.6 Luna"
  | "GPT 6 Sol"
  | "Gemini 1.5 Pro"
  | "Grok 4"
  | "Space Bunny Alpha"
  | "Qwen 3.8 27B"
  | "GLM 5.3"
  | "Kimi K3"
  | "Laguna XS 2.1"
  | "Muse Glimmer 30B"
  | "Grok 4.5"
  | "Claude Sonnet 4"
  | "Claude Sonnet 5.5"
  | "Gemini 2.5 Flash"
  | "Gemini 2.5 Pro"
  | "GPT 6 Astra"
  | "GPT 5.6 Sol"
  | "Gemma 4 31B IT"
  | "Claude Opus 4.5"
  | "Laguna XS 2 1"
  | "Claude Fable 5.1"
  | "Claude Opus 5.5"
  | "GPT 5"
  | "Gemini 2.0 Flash"
  | "Grok 4.3"
  | "LongCat 2.5 Preview"
  | "Pixel Canary"
  | "GPT OSS 120B"
  | "Grok 4.20"
  | "Claude Opus 5"
  | "Claude Sonnet 3.5"
  | "GPT 5.5"
  | "GPT 6 Luna"
  | "Gemini 2.5"
  | "Gemini 2 Flash"
  | "Gemini 3 Flash";

export interface SourceDef {
  key: SourceKey;
  label: string;
  file: string;
}

export const SOURCE_DEFS: SourceDef[] = [
  { key: "average", label: "Average", file: "average.md" },
  { key: "big-pickle", label: "Big Pickle", file: "Big_Pickle.md" },
  { key: "Muse Spark 1.3", label: "Muse Spark 1.3", file: "Muse_Spark_1.3.md" },
  { key: "Gemini 3.5 Flash Lite", label: "Gemini 3.5 Flash Lite", file: "Gemini_3.5_Flash_Lite.md" },
  { key: "Gemini 3.6 Flash", label: "Gemini 3.6 Flash", file: "Gemini_3.6_Flash.md" },
  { key: "GLM 5.3 Flash", label: "GLM 5.3 Flash", file: "GLM_5.3_Flash.md" },
  { key: "Ox Alpha", label: "Ox Alpha", file: "Ox_Alpha.md" },
  { key: "Claude Sonnet 4.6", label: "Claude Sonnet 4.6", file: "Claude_Sonnet_4.6.md" },
  { key: "DeepSeek 4.1 Flash", label: "DeepSeek 4.1 Flash", file: "DeepSeek_4.1_Flash.md" },
  { key: "Solar Pro 4", label: "Solar Pro 4", file: "Solar_Pro_4.md" },
  { key: "MiniMax M3", label: "MiniMax M3", file: "MiniMax_M3.md" },
  { key: "GPT 5.6 Terra", label: "GPT 5.6 Terra", file: "GPT_5.6_Terra.md" },
  { key: "Gemini 3.5 Flash", label: "Gemini 3.5 Flash", file: "Gemini_3.5_Flash.md" },
  { key: "Claude Opus 4.6", label: "Claude Opus 4.6", file: "Claude_Opus_4.6.md" },
  { key: "Gemini 3.8 Flash", label: "Gemini 3.8 Flash", file: "Gemini_3.8_Flash.md" },
  { key: "Grok 4.6", label: "Grok 4.6", file: "Grok_4.6.md" },
  { key: "Gemini 3.7 Flash", label: "Gemini 3.7 Flash", file: "Gemini_3.7_Flash.md" },
  { key: "Laguna S 2.1", label: "Laguna S 2.1", file: "Laguna_S_2.1.md" },
  { key: "GLM 5.2 Coding", label: "GLM 5.2 Coding", file: "GLM_5.2_Coding.md" },
  { key: "Mimo v2.6 Flash", label: "MiMo V2.6 Flash", file: "Mimo_v2.6_Flash.md" },
  { key: "tool", label: "Tool", file: "average.md" },
  { key: "reason", label: "Reason", file: "average.md" },
  { key: "context", label: "Context", file: "average.md" },
  { key: "cost", label: "Cost", file: "average.md" },
  { key: "code", label: "Code", file: "average.md" },
  { key: "multi", label: "Multi", file: "average.md" },
  { key: "Mimo v2.5 Free", label: "MiMo V2.5 Free", file: "Mimo_v2.5_Free.md" },
  { key: "Muse Spark 1.2", label: "Muse Spark 1.2", file: "Muse_Spark_1.2.md" },
  { key: "Claude Sonnet 4.5", label: "Claude Sonnet 4.5", file: "Claude_Sonnet_4.5.md" },
  { key: "Claude Sonnet 5", label: "Claude Sonnet 5", file: "Claude_Sonnet_5.md" },
  { key: "GPT 5.6 Luna", label: "GPT 5.6 Luna", file: "GPT_5.6_Luna.md" },
  { key: "GPT 6 Sol", label: "GPT 6 Sol", file: "GPT_6_Sol.md" },
  { key: "Gemini 1.5 Pro", label: "Gemini 1.5 Pro", file: "Gemini_1.5_Pro.md" },
  { key: "Grok 4", label: "Grok 4", file: "Grok_4.md" },
  { key: "Space Bunny Alpha", label: "Space Bunny Alpha", file: "Space_Bunny_Alpha.md" },
  { key: "Qwen 3.8 27B", label: "Qwen 3.8 27B", file: "Qwen_3.8_27B.md" },
  { key: "GLM 5.3", label: "GLM 5.3", file: "GLM_5.3.md" },
  { key: "Kimi K3", label: "Kimi K3", file: "Kimi_K3.md" },
  { key: "Laguna XS 2.1", label: "Laguna XS 2.1", file: "Laguna_XS_2.1.md" },
  { key: "Muse Glimmer 30B", label: "Muse Glimmer 30B", file: "Muse_Glimmer_30B.md" },
  { key: "Grok 4.5", label: "Grok 4.5", file: "Grok_4.5.md" },
  { key: "Claude Sonnet 4", label: "Claude Sonnet 4", file: "Claude_Sonnet_4.md" },
  { key: "Claude Sonnet 5.5", label: "Claude Sonnet 5.5", file: "Claude_Sonnet_5.5.md" },
  { key: "Gemini 2.5 Flash", label: "Gemini 2.5 Flash", file: "Gemini_2.5_Flash.md" },
  { key: "Gemini 2.5 Pro", label: "Gemini 2.5 Pro", file: "Gemini_2.5_Pro.md" },
  { key: "GPT 6 Astra", label: "GPT 6 Astra", file: "GPT_6_Astra.md" },
  { key: "GPT 5.6 Sol", label: "GPT 5.6 Sol", file: "GPT_5.6_Sol.md" },
  { key: "Gemma 4 31B IT", label: "Gemma 4 31B IT", file: "Gemma_4_31B_IT.md" },
  { key: "Claude Opus 4.5", label: "Claude Opus 4.5", file: "Claude_Opus_4.5.md" },
  { key: "Laguna XS 2 1", label: "Laguna XS 2 1", file: "Laguna_XS_2_1.md" },
  { key: "Claude Fable 5.1", label: "Claude Fable 5.1", file: "Claude_Fable_5.1.md" },
  { key: "Claude Opus 5.5", label: "Claude Opus 5.5", file: "Claude_Opus_5.5.md" },
  { key: "GPT 5", label: "GPT 5", file: "GPT_5.md" },
  { key: "Gemini 2.0 Flash", label: "Gemini 2.0 Flash", file: "Gemini_2.0_Flash.md" },
  { key: "Grok 4.3", label: "Grok 4.3", file: "Grok_4.3.md" },
  { key: "LongCat 2.5 Preview", label: "LongCat 2.5 Preview", file: "LongCat_2.5_Preview.md" },
  { key: "Pixel Canary", label: "Pixel Canary", file: "Pixel_Canary.md" },
  { key: "GPT OSS 120B", label: "GPT OSS 120B", file: "GPT_OSS_120B.md" },
  { key: "Grok 4.20", label: "Grok 4.20", file: "Grok_4.20.md" },
  { key: "Claude Opus 5", label: "Claude Opus 5", file: "Claude_Opus_5.md" },
  { key: "Claude Sonnet 3.5", label: "Claude Sonnet 3.5", file: "Claude_Sonnet_3.5.md" },
  { key: "GPT 5.5", label: "GPT 5.5", file: "GPT_5.5.md" },
  { key: "GPT 6 Luna", label: "GPT 6 Luna", file: "GPT_6_Luna.md" },
  { key: "Gemini 2.5", label: "Gemini 2.5", file: "Gemini_2.5.md" },
  { key: "Gemini 2 Flash", label: "Gemini 2 Flash", file: "Gemini_2_Flash.md" },
  { key: "Gemini 3 Flash", label: "Gemini 3 Flash", file: "Gemini_3_Flash.md" },
];
