// AUTO-GENERATED by `pnpm sync` (scripts/sync-data.mjs). Do not hand-edit.
// Registry of reporting agents. Virtual sort views live in src/data/models.ts,
// never here.

/** Rater gate: only reports by models with own Overall above this count (managed by `pnpm sync` from scripts/lib/parse.mjs — do not hand-edit). */
export const RATER_GATE = 84.9;

export type SourceKey =
  | "average"
  | "big-pickle"
  | "Muse Spark 1.3"
  | "Gemini 3.5 Flash Lite"
  | "Gemini 3.6 Flash"
  | "GLM 5.3 Flash"
  | "Ox Alpha"
  | "Claude Sonnet 4.6"
  | "DeepSeek 4.1 Flash"
  | "Solar Pro 4"
  | "MiniMax M3"
  | "GPT 5.6 Terra"
  | "Gemini 3.5 Flash"
  | "Claude Opus 4.6"
  | "Gemini 3.8 Flash"
  | "Grok 4.6"
  | "Gemini 3.7 Flash"
  | "Laguna S 2.1"
  | "GLM 5.2 Coding"
  | "Mimo v2.6 Flash"
  | "Mimo v2.5 Free"
  | "Muse Spark 1.2"
  | "Claude Sonnet 4.5"
  | "Claude Sonnet 5"
  | "GPT 5.6 Luna"
  | "GPT 6 Sol"
  | "Gemini 1.5 Pro"
  | "Grok 4"
  | "Space Bunny"
  | "Qwen 3.8 27B"
  | "GLM 5.3"
  | "Kimi K3"
  | "Laguna XS 2.1"
  | "Grok 4.5"
  | "Claude Sonnet 4"
  | "Claude Sonnet 5.5"
  | "Gemini 2.5 Flash"
  | "Gemini 2.5 Pro"
  | "GPT 6 Astra"
  | "GPT 5.6 Sol"
  | "Gemma 4 31B IT"
  | "Claude Opus 4.5"
  | "Laguna XS 2 1"
  | "Claude Fable 5.1"
  | "Claude Opus 5.5"
  | "GPT 5"
  | "Gemini 2.0 Flash"
  | "Grok 4.3"
  | "LongCat 2.5 Preview"
  | "Pixel Canary"
  | "GPT OSS 120B"
  | "Grok 4.20"
  | "Claude Opus 5"
  | "Claude Sonnet 3.5"
  | "GPT 5.5"
  | "GPT 6 Luna"
  | "Gemini 2.5"
  | "Gemini 2 Flash"
  | "Gemini 3 Flash"
  | "DeepSeek 4 Flash"
  | "Claude Sonnet 3.7"
  | "Qwen 3.8 Flash"
  | "Fledge Alpha"
  | "North Mini Code"
  | "Ling 3.1 Flash"
  | "Claude Opus 4.8";

/** Virtual sort views for the results-source dropdown (not reporting agents). */
export type ViewKey = "tool" | "reason" | "context" | "cost" | "code" | "multi";

/** Any selectable results-source value: a real source or a virtual view. */
export type ResultsView = ViewKey | SourceKey;

export interface SourceDef {
  key: SourceKey;
  label: string;
  file: string;
  /** Tracked model-page slug for this reporting agent, when one exists. */
  slug?: string;
}

export const SOURCE_DEFS: SourceDef[] = [
  { key: "average", label: "Average", file: "average.md" },
  { key: "big-pickle", label: "Big Pickle", file: "Big_Pickle.md", slug: "big-pickle" },
  { key: "Muse Spark 1.3", label: "Muse Spark 1.3", file: "Muse_Spark_1.3.md", slug: "muse-spark-1.3" },
  { key: "Gemini 3.5 Flash Lite", label: "Gemini 3.5 Flash Lite", file: "Gemini_3.5_Flash_Lite.md", slug: "gemini-3.5-flash-lite" },
  { key: "Gemini 3.6 Flash", label: "Gemini 3.6 Flash", file: "Gemini_3.6_Flash.md", slug: "gemini-3.6-flash" },
  { key: "GLM 5.3 Flash", label: "GLM 5.3 Flash", file: "GLM_5.3_Flash.md", slug: "glm-5.3-flash" },
  { key: "Ox Alpha", label: "Ox Alpha", file: "Ox_Alpha.md", slug: "ox_alpha" },
  { key: "Claude Sonnet 4.6", label: "Claude Sonnet 4.6", file: "Claude_Sonnet_4.6.md", slug: "claude-sonnet-4.6" },
  { key: "DeepSeek 4.1 Flash", label: "DeepSeek v4.1 Flash", file: "DeepSeek_4.1_Flash.md", slug: "deepseek-v4.1-flash" },
  { key: "Solar Pro 4", label: "Solar Pro 4", file: "Solar_Pro_4.md", slug: "solar-pro-4" },
  { key: "MiniMax M3", label: "MiniMax M3", file: "MiniMax_M3.md", slug: "minimax-m3" },
  { key: "GPT 5.6 Terra", label: "GPT 5.6 Terra", file: "GPT_5.6_Terra.md", slug: "gpt-5.6-terra" },
  { key: "Gemini 3.5 Flash", label: "Gemini 3.5 Flash", file: "Gemini_3.5_Flash.md", slug: "gemini-3.5-flash" },
  { key: "Claude Opus 4.6", label: "Claude Opus 4.6", file: "Claude_Opus_4.6.md", slug: "claude-opus-4.6" },
  { key: "Gemini 3.8 Flash", label: "Gemini 3.8 Flash", file: "Gemini_3.8_Flash.md", slug: "gemini-3.8-flash" },
  { key: "Grok 4.6", label: "Grok 4.6", file: "Grok_4.6.md", slug: "grok-4.6" },
  { key: "Gemini 3.7 Flash", label: "Gemini 3.7 Flash", file: "Gemini_3.7_Flash.md", slug: "gemini-3.7-flash" },
  { key: "Laguna S 2.1", label: "Laguna S 2.1", file: "Laguna_S_2.1.md", slug: "laguna-s-2.1" },
  { key: "GLM 5.2 Coding", label: "GLM 5.2 Coding", file: "GLM_5.2_Coding.md", slug: "glm-5.2-coding" },
  { key: "Mimo v2.6 Flash", label: "MiMo v2.6 Flash", file: "Mimo_v2.6_Flash.md", slug: "mimo-v2.6-free" },
  { key: "Mimo v2.5 Free", label: "MiMo v2.5 Free", file: "Mimo_v2.5_Free.md", slug: "mimo-v2.5-free" },
  { key: "Muse Spark 1.2", label: "Muse Spark 1.2", file: "Muse_Spark_1.2.md", slug: "muse-spark-1.2" },
  { key: "Claude Sonnet 4.5", label: "Claude Sonnet 4.5", file: "Claude_Sonnet_4.5.md", slug: "claude-sonnet-4.5" },
  { key: "Claude Sonnet 5", label: "Claude Sonnet 5", file: "Claude_Sonnet_5.md", slug: "claude-sonnet-5" },
  { key: "GPT 5.6 Luna", label: "GPT 5.6 Luna", file: "GPT_5.6_Luna.md", slug: "gpt-5.6-luna" },
  { key: "GPT 6 Sol", label: "GPT 6 Sol", file: "GPT_6_Sol.md", slug: "gpt-6-sol" },
  { key: "Gemini 1.5 Pro", label: "Gemini 1.5 Pro", file: "Gemini_1.5_Pro.md", slug: "gemini-1.5-pro" },
  { key: "Grok 4", label: "Grok 4", file: "Grok_4.md", slug: "grok-4" },
  { key: "Space Bunny", label: "Space Bunny", file: "Space_Bunny.md", slug: "space-bunny" },
  { key: "Qwen 3.8 27B", label: "Qwen 3.8 27B", file: "Qwen_3.8_27B.md", slug: "qwen-3.8-27b" },
  { key: "GLM 5.3", label: "GLM 5.3", file: "GLM_5.3.md", slug: "glm-5.3" },
  { key: "Kimi K3", label: "Kimi K3", file: "Kimi_K3.md", slug: "kimi-k3" },
  { key: "Laguna XS 2.1", label: "Laguna XS 2.1", file: "Laguna_XS_2.1.md", slug: "laguna-xs-2.1" },
  { key: "Grok 4.5", label: "Grok 4.5", file: "Grok_4.5.md", slug: "grok-4.5" },
  { key: "Claude Sonnet 4", label: "Claude Sonnet 4", file: "Claude_Sonnet_4.md", slug: "claude-sonnet-4" },
  { key: "Claude Sonnet 5.5", label: "Claude Sonnet 5.5", file: "Claude_Sonnet_5.5.md", slug: "claude-sonnet-5.5" },
  { key: "Gemini 2.5 Flash", label: "Gemini 2.5 Flash", file: "Gemini_2.5_Flash.md", slug: "gemini-2.5-flash" },
  { key: "Gemini 2.5 Pro", label: "Gemini 2.5 Pro", file: "Gemini_2.5_Pro.md", slug: "gemini-2.5-pro" },
  { key: "GPT 6 Astra", label: "GPT 6 Astra", file: "GPT_6_Astra.md", slug: "gpt-6-astra" },
  { key: "GPT 5.6 Sol", label: "GPT 5.6 Sol", file: "GPT_5.6_Sol.md", slug: "gpt-5.6-sol" },
  { key: "Gemma 4 31B IT", label: "Gemma 4 31B IT", file: "Gemma_4_31B_IT.md" },
  { key: "Claude Opus 4.5", label: "Claude Opus 4.5", file: "Claude_Opus_4.5.md", slug: "claude-opus-4.5" },
  { key: "Laguna XS 2 1", label: "Laguna XS 2 1", file: "Laguna_XS_2_1.md", slug: "laguna-xs-2.1" },
  { key: "Claude Fable 5.1", label: "Claude Fable 5.1", file: "Claude_Fable_5.1.md", slug: "claude-fable-5.1" },
  { key: "Claude Opus 5.5", label: "Claude Opus 5.5", file: "Claude_Opus_5.5.md", slug: "claude-opus-5.5" },
  { key: "GPT 5", label: "GPT 5", file: "GPT_5.md", slug: "gpt-5" },
  { key: "Gemini 2.0 Flash", label: "Gemini 2.0 Flash", file: "Gemini_2.0_Flash.md", slug: "gemini-2.0-flash" },
  { key: "Grok 4.3", label: "Grok 4.3", file: "Grok_4.3.md", slug: "grok-4.3" },
  { key: "LongCat 2.5 Preview", label: "LongCat 2.5 Preview", file: "LongCat_2.5_Preview.md", slug: "longcat_2.5_preview" },
  { key: "Pixel Canary", label: "Pixel Canary", file: "Pixel_Canary.md", slug: "pixel_canary" },
  { key: "GPT OSS 120B", label: "GPT OSS 120B", file: "GPT_OSS_120B.md", slug: "gpt-oss-120b" },
  { key: "Grok 4.20", label: "Grok 4.20", file: "Grok_4.20.md", slug: "grok-4.20" },
  { key: "Claude Opus 5", label: "Claude Opus 5", file: "Claude_Opus_5.md", slug: "claude-opus-5" },
  { key: "Claude Sonnet 3.5", label: "Claude Sonnet 3.5", file: "Claude_Sonnet_3.5.md", slug: "claude-sonnet-3.5" },
  { key: "GPT 5.5", label: "GPT 5.5", file: "GPT_5.5.md", slug: "gpt-5.5" },
  { key: "GPT 6 Luna", label: "GPT 6 Luna", file: "GPT_6_Luna.md", slug: "gpt-6-luna" },
  { key: "Gemini 2.5", label: "Gemini 2.5", file: "Gemini_2.5.md", slug: "gemini-2.5" },
  { key: "Gemini 2 Flash", label: "Gemini 2 Flash", file: "Gemini_2_Flash.md" },
  { key: "Gemini 3 Flash", label: "Gemini 3 Flash", file: "Gemini_3_Flash.md", slug: "gemini-3-flash" },
  { key: "DeepSeek 4 Flash", label: "DeepSeek 4 Flash", file: "DeepSeek_4_Flash.md" },
  { key: "Claude Sonnet 3.7", label: "Claude Sonnet 3.7", file: "Claude_Sonnet_3.7.md", slug: "claude-sonnet-3.7" },
  { key: "Qwen 3.8 Flash", label: "Qwen 3.8 Flash", file: "Qwen_3.8_Flash.md", slug: "qwen-3.8-flash" },
  { key: "Fledge Alpha", label: "Fledge Alpha", file: "Fledge_Alpha.md", slug: "fledge-alpha" },
  { key: "North Mini Code", label: "North Mini Code", file: "North_Mini_Code.md", slug: "north_mini_code" },
  { key: "Ling 3.1 Flash", label: "Ling 3.1 Flash", file: "Ling_3.1_Flash.md", slug: "ling-3.1-flash" },
  { key: "Claude Opus 4.8", label: "Claude Opus 4.8", file: "Claude_Opus_4.8.md", slug: "claude-opus-4.8" },
];
